version: "3"
services:
  api:
    build:
      context: .
    environment:
      - LISTEN_HOST=0.0.0.0
      - LISTEN_PORT=8080
      - POSTGRES_USER=lev
      - POSTGRES_PASSWORD=lev
      - POSTGRES_HOST=postgres
      - POSTGRES_ADMIN_USER=root
      - POSTGRES_ADMIN_PASSWORD=root
      - POSTGRES_SSL=FALSE
    ports:
      - "80:8080"
  postgres:
    build:
      context: example-db/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=lev
      - APP_USER=lev
      - APP_PASSWORD=lev
    ports:
      - "5432:5432"
